### ISSUE TITLE
unable to load under linux, on windows works fine

### ISSUE THREAD

**Issue by ghost** [tnkemdilim/Money-To-Words-Converter#4] opened 2018-01-17 03:00 UTC
installed on openSUSE Server Leap 42.3

when run in app following occurs:

Fatal error: Class 'MoneyToWords\MoneyToWordsConverter' not found in /srv/www/htdocs/realoffer/dashboard.php on line 423

but same code is working fine on windows dev machine under phpED IDE

coded as:

  require 'vendor/autoload.php';
  use MoneyToWords\MoneyToWordsConverter;
  
  $Testmoney = 1250000;
  $converter = new MoneyToWordsConverter($Testmoney, "dollars");
  echo ($converter->Convert());  

directory structures identical under linux and windows

**Comment by toksdotdev** [comment] 2018-01-20 11:59
I'll try reproduce the error,  and give a fix shortly.

**Comment by toksdotdev** [comment] 2018-01-22 03:20
Sorry, do you mind if you post the full code.

Also, what are you using to auto-load the files e.g. composer etc.

Also if try to switch between ```<?php ... ?>``` to ```<? ... ```. As some servers do not recognize both.

Lastly, I'm so sorry for the inconvenience this might have caused.

**Comment by toksdotdev** [comment] 2018-05-28 16:25
Since I haven't gotten a response, I'll kindly close the issue.

**Closed as completed by toksdotdev** 2018-05-28 16:25 UTC
